sudo: false

language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - composer update --no-interaction --prefer-dist
  - composer require php-coveralls/php-coveralls

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - php vendor/bin/php-coveralls -v

cache:
  directories:
    - $HOME/.composer/cache/files
